from enum import StrEnum


class Intent(StrEnum):
    CREATE_PRODUCTION_REQUEST = "CREATE_PRODUCTION_REQUEST"
    PAUSE_JOB = "PAUSE_JOB"
    RESUME_JOB = "RESUME_JOB"
    CANCEL_JOB = "CANCEL_JOB"
    QUERY_JOB_STATUS = "QUERY_JOB_STATUS"
    QUERY_INVENTORY = "QUERY_INVENTORY"
    UNKNOWN = "UNKNOWN"
