"""fix_dbs2"""
revision = '59321fa37472'
down_revision = '034f64cfe733'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_bom_items',
    sa.Column('bom_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('bom_item_id'),
    sa.UniqueConstraint('product_id', 'part_id', name='uq_product_bom_product_part')
    )
    op.create_table('product_roof_option_parts',
    sa.Column('roof_option_part_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('roof_option_code', postgresql.ENUM('ROOF_01', 'ROOF_02', name='roof_option_code', create_type=False), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('expected_stage_operation_code', sa.String(length=100), nullable=False),
    sa.Column('pick_zone', sa.String(length=100), nullable=True),
    sa.Column('execution_gate', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('roof_option_part_id'),
    sa.UniqueConstraint('product_code', 'roof_option_code', 'part_id', name='uq_product_roof_option_parts_product_option_part')
    )
    op.create_table('assembly_recipe_stage_parts',
    sa.Column('recipe_stage_part_id', sa.Integer(), nullable=False),
    sa.Column('recipe_stage_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('pick_zone', sa.String(length=100), nullable=True),
    sa.Column('execution_gate', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_stage_id'], ['assembly_recipe_stages.recipe_stage_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recipe_stage_part_id'),
    sa.UniqueConstraint('recipe_stage_id', 'part_id', name='uq_assembly_recipe_stage_parts_stage_part')
    )
    op.create_table('product_roof_option_part_installation_slots',
    sa.Column('roof_part_slot_id', sa.Integer(), nullable=False),
    sa.Column('roof_option_part_id', sa.Integer(), nullable=False),
    sa.Column('installation_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['installation_slot_id'], ['installation_slots.installation_slot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['roof_option_part_id'], ['product_roof_option_parts.roof_option_part_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('roof_part_slot_id'),
    sa.UniqueConstraint('roof_option_part_id', 'installation_slot_id', name='uq_roof_option_part_slots_part_slot')
    )
    op.create_table('assembly_recipe_stage_part_installation_slots',
    sa.Column('stage_part_slot_id', sa.Integer(), nullable=False),
    sa.Column('recipe_stage_part_id', sa.Integer(), nullable=False),
    sa.Column('installation_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['installation_slot_id'], ['installation_slots.installation_slot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_stage_part_id'], ['assembly_recipe_stage_parts.recipe_stage_part_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stage_part_slot_id'),
    sa.UniqueConstraint('recipe_stage_part_id', 'installation_slot_id', name='uq_stage_part_slots_part_slot')
    )
    op.create_table('production_inspection_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('measured_value', sa.String(length=200), nullable=True),
    sa.Column('expected_value', sa.String(length=200), nullable=True),
    sa.Column('tolerance_info', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['production_inspections.inspection_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.drop_constraint(op.f('fk_stage_part'), 'assembly_recipe_stages', type_='foreignkey')
    op.drop_constraint(op.f('fk_stage_slot'), 'assembly_recipe_stages', type_='foreignkey')
    op.drop_column('assembly_recipe_stages', 'option_code')
    op.drop_column('assembly_recipe_stages', 'installation_slot_id')
    op.drop_column('assembly_recipe_stages', 'execution_gate')
    op.drop_column('assembly_recipe_stages', 'part_id')
    op.drop_column('assembly_recipe_stages', 'quantity')
    op.drop_column('assembly_recipe_stages', 'pick_zone')
    op.drop_constraint(op.f('assembly_recipes_product_code_fkey'), 'assembly_recipes', type_='foreignkey')
    op.add_column('installation_slots', sa.Column('display_name', sa.String(length=150), nullable=False))
    op.add_column('installation_slots', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('installation_slots', 'slot_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_installation_slots_code'), 'installation_slots', type_='unique')
    op.create_unique_constraint('uq_installation_slots_product_code', 'installation_slots', ['product_id', 'slot_code'])
    op.drop_constraint(op.f('ck_installation_slots_code_nonblank'), 'installation_slots', type_='check')
    op.execute("ALTER TYPE job_material_delivery_status RENAME TO material_delivery_status")
    op.drop_constraint(op.f('uq_job_material_deliveries_order'), 'job_material_deliveries', type_='unique')
    op.alter_column('job_material_delivery_items', 'job_delivery_item_id', new_column_name='delivery_item_id')
    op.add_column('job_material_delivery_items', sa.Column('is_delivered', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('job_material_delivery_items_source_delivery_batch_item_id_fkey'), 'job_material_delivery_items', type_='foreignkey')
    op.drop_constraint(op.f('ck_job_material_delivery_items_quantity_positive'), 'job_material_delivery_items', type_='check')
    op.create_check_constraint('ck_job_material_delivery_items_quantity', 'job_material_delivery_items', 'quantity >= 1')
    op.drop_column('job_material_delivery_items', 'source_delivery_batch_item_id')
    op.execute("ALTER TYPE job_material_feed_status RENAME TO material_feed_status")
    op.alter_column('job_step_delivery_dependencies', 'job_step_delivery_dependency_id', new_column_name='step_dependency_id')
    op.add_column('job_step_delivery_dependencies', sa.Column('is_enforced', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('job_steps', 'step_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_steps', 'operation_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('job_steps', 'display_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_index(op.f('uq_job_steps_runtime_roof'), table_name='job_steps', postgresql_where="((operation_code)::text = 'INSTALL_ROOF'::text)")
    op.drop_constraint(op.f('fk_job_steps_source_recipe_stage'), 'job_steps', type_='foreignkey')
    op.drop_constraint(op.f('fk_jobstep_part'), 'job_steps', type_='foreignkey')
    op.drop_constraint(op.f('fk_jobstep_slot'), 'job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'job_steps', 'assembly_recipe_stages', ['source_recipe_stage_id'], ['recipe_stage_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ck_job_steps_recipe_snapshot'), 'job_steps', type_='check')
    op.drop_column('job_steps', 'roof_option_code')
    op.drop_column('job_steps', 'installation_slot_id')
    op.drop_column('job_steps', 'part_id')
    op.drop_column('job_steps', 'quantity')
    op.drop_column('job_steps', 'pick_zone')
    op.alter_column('material_delivery_batch_items', 'delivery_batch_item_id', new_column_name='batch_item_id')
    op.drop_constraint(op.f('uq_material_delivery_batch_items_part'), 'material_delivery_batch_items', type_='unique')
    op.create_unique_constraint('uq_material_delivery_batch_items_batch_part', 'material_delivery_batch_items', ['delivery_batch_id', 'part_id'])
    op.drop_constraint(op.f('ck_material_delivery_batch_items_quantity_positive'), 'material_delivery_batch_items', type_='check')
    op.add_column('material_delivery_batches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_material_delivery_batches_order'), 'material_delivery_batches', type_='unique')
    op.drop_constraint(op.f('ck_material_delivery_batches_order_positive'), 'material_delivery_batches', type_='check')
    op.drop_index(op.f('uq_material_delivery_plans_active_recipe'), table_name='material_delivery_plans', postgresql_where='is_active')
    op.create_index('idx_material_delivery_plans_active_per_recipe', 'material_delivery_plans', ['assembly_recipe_id'], unique=True, postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.drop_index(op.f('ix_pending_production_requests_expires_at'), table_name='pending_production_requests')
    op.drop_index(op.f('uq_pending_production_requests_active_session'), table_name='pending_production_requests', postgresql_where="(state = ANY (ARRAY['WAITING_ROOF_OPTION'::pending_production_state, 'AWAITING_CONFIRMATION'::pending_production_state]))")
    op.drop_constraint(op.f('pending_production_requests_product_code_fkey'), 'pending_production_requests', type_='foreignkey')
    op.add_column('production_inspections', sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('production_inspections', sa.Column('is_passed', sa.Boolean(), nullable=True))
    op.drop_column('production_inspections', 'created_at')
    op.drop_constraint(op.f('uq_production_jobs_pending_source_item'), 'production_jobs', type_='unique')
    op.drop_constraint(op.f('fk_production_jobs_material_delivery_plan'), 'production_jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_production_jobs_source_pending_request'), 'production_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'production_jobs', 'pending_production_requests', ['source_pending_request_id'], ['request_id'], ondelete='SET NULL', use_alter=True)
    op.drop_constraint(op.f('ck_production_jobs_pending_source_pair'), 'production_jobs', type_='check')
    op.drop_column('production_jobs', 'material_delivery_plan_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_jobs', sa.Column('material_delivery_plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_production_jobs_pending_source_pair'), 'production_jobs', 'source_pending_request_id IS NULL AND source_item_index IS NULL OR source_pending_request_id IS NOT NULL AND source_item_index IS NOT NULL AND source_item_index >= 1')
    op.drop_constraint(None, 'production_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_production_jobs_source_pending_request'), 'production_jobs', 'pending_production_requests', ['source_pending_request_id'], ['request_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_production_jobs_material_delivery_plan'), 'production_jobs', 'material_delivery_plans', ['material_delivery_plan_id'], ['delivery_plan_id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('uq_production_jobs_pending_source_item'), 'production_jobs', ['source_pending_request_id', 'source_item_index'], postgresql_nulls_not_distinct=False)
    op.add_column('production_inspections', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('production_inspections', 'is_passed')
    op.drop_column('production_inspections', 'requested_at')
    op.create_foreign_key(op.f('pending_production_requests_product_code_fkey'), 'pending_production_requests', 'products', ['product_code'], ['product_code'], ondelete='RESTRICT')
    op.create_index(op.f('uq_pending_production_requests_active_session'), 'pending_production_requests', ['session_id'], unique=True, postgresql_where="(state = ANY (ARRAY['WAITING_ROOF_OPTION'::pending_production_state, 'AWAITING_CONFIRMATION'::pending_production_state]))")
    op.create_index(op.f('ix_pending_production_requests_expires_at'), 'pending_production_requests', ['expires_at'], unique=False)
    op.drop_index('idx_material_delivery_plans_active_per_recipe', table_name='material_delivery_plans', postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.create_index(op.f('uq_material_delivery_plans_active_recipe'), 'material_delivery_plans', ['assembly_recipe_id'], unique=True, postgresql_where='is_active')
    op.create_check_constraint(op.f('ck_material_delivery_batches_order_positive'), 'material_delivery_batches', 'batch_order >= 1')
    op.create_unique_constraint(op.f('uq_material_delivery_batches_order'), 'material_delivery_batches', ['delivery_plan_id', 'batch_order'], postgresql_nulls_not_distinct=False)
    op.drop_column('material_delivery_batches', 'created_at')
    op.add_column('material_delivery_batch_items', sa.Column('delivery_batch_item_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_check_constraint(op.f('ck_material_delivery_batch_items_quantity_positive'), 'material_delivery_batch_items', 'quantity >= 1')
    op.drop_constraint('uq_material_delivery_batch_items_batch_part', 'material_delivery_batch_items', type_='unique')
    op.create_unique_constraint(op.f('uq_material_delivery_batch_items_part'), 'material_delivery_batch_items', ['delivery_batch_id', 'part_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('material_delivery_batch_items', 'batch_item_id')
    op.add_column('job_steps', sa.Column('pick_zone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('job_steps', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_steps', sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_steps', sa.Column('installation_slot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_steps', sa.Column('roof_option_code', postgresql.ENUM('ROOF_01', 'ROOF_02', name='roof_option_code'), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_job_steps_recipe_snapshot'), 'job_steps', 'source_recipe_stage_id IS NULL OR step_order IS NOT NULL AND operation_code IS NOT NULL AND display_name IS NOT NULL')
    op.drop_constraint(None, 'job_steps', type_='foreignkey')
    op.create_foreign_key(op.f('fk_jobstep_slot'), 'job_steps', 'installation_slots', ['installation_slot_id'], ['installation_slot_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_jobstep_part'), 'job_steps', 'parts', ['part_id'], ['part_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_job_steps_source_recipe_stage'), 'job_steps', 'assembly_recipe_stages', ['source_recipe_stage_id'], ['recipe_stage_id'], ondelete='RESTRICT')
    op.create_index(op.f('uq_job_steps_runtime_roof'), 'job_steps', ['job_id'], unique=True, postgresql_where="((operation_code)::text = 'INSTALL_ROOF'::text)")
    op.alter_column('job_steps', 'display_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('job_steps', 'operation_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('job_steps', 'step_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('job_step_delivery_dependencies', sa.Column('job_step_delivery_dependency_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('job_step_delivery_dependencies', 'is_enforced')
    op.drop_column('job_step_delivery_dependencies', 'step_dependency_id')
    op.alter_column('job_material_feed_executions', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='material_feed_status'),
               type_=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='job_material_feed_status'),
               existing_nullable=False)
    op.add_column('job_material_delivery_items', sa.Column('source_delivery_batch_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('job_material_delivery_items', sa.Column('job_delivery_item_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('ck_job_material_delivery_items_quantity', 'job_material_delivery_items', type_='check')
    op.create_check_constraint(op.f('ck_job_material_delivery_items_quantity_positive'), 'job_material_delivery_items', 'quantity >= 1')
    op.create_foreign_key(op.f('job_material_delivery_items_source_delivery_batch_item_id_fkey'), 'job_material_delivery_items', 'material_delivery_batch_items', ['source_delivery_batch_item_id'], ['delivery_batch_item_id'], ondelete='RESTRICT')
    op.drop_column('job_material_delivery_items', 'is_delivered')
    op.drop_column('job_material_delivery_items', 'delivery_item_id')
    op.create_unique_constraint(op.f('uq_job_material_deliveries_order'), 'job_material_deliveries', ['production_job_id', 'batch_order'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_material_deliveries', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='material_delivery_status'),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='job_material_delivery_status'),
               existing_nullable=False)
    op.create_check_constraint(op.f('ck_installation_slots_code_nonblank'), 'installation_slots', 'length(TRIM(BOTH FROM slot_code)) > 0')
    op.drop_constraint('uq_installation_slots_product_code', 'installation_slots', type_='unique')
    op.create_unique_constraint(op.f('uq_installation_slots_code'), 'installation_slots', ['slot_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('installation_slots', 'slot_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('installation_slots', 'is_active')
    op.drop_column('installation_slots', 'display_name')
    op.create_foreign_key(op.f('assembly_recipes_product_code_fkey'), 'assembly_recipes', 'products', ['product_code'], ['product_code'], ondelete='RESTRICT')
    op.add_column('assembly_recipe_stages', sa.Column('pick_zone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('assembly_recipe_stages', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assembly_recipe_stages', sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assembly_recipe_stages', sa.Column('execution_gate', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('assembly_recipe_stages', sa.Column('installation_slot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assembly_recipe_stages', sa.Column('option_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_stage_slot'), 'assembly_recipe_stages', 'installation_slots', ['installation_slot_id'], ['installation_slot_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_stage_part'), 'assembly_recipe_stages', 'parts', ['part_id'], ['part_id'], ondelete='RESTRICT')
    op.drop_table('production_inspection_results')
    op.drop_table('assembly_recipe_stage_part_installation_slots')
    op.drop_table('product_roof_option_part_installation_slots')
    op.drop_table('assembly_recipe_stage_parts')
    op.drop_table('product_roof_option_parts')
    op.drop_table('product_bom_items')
    # ### end Alembic commands ###
