"""Add execution_attempts table"""
revision = '5a7815347783'
down_revision = '5aa0e4bd35e8'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.String(length=100), nullable=False),
    sa.Column('executor_type', sa.Enum('ROBOT_CELL', 'FORKLIFT', name='executor_type'), nullable=False),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_step_id', sa.Integer(), nullable=True),
    sa.Column('job_delivery_id', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'DISPATCHING', 'ACCEPTED', 'SUCCEEDED', 'FAILED', 'CANCELED', 'UNKNOWN', name='execution_attempt_status'), nullable=False),
    sa.Column('request_payload_json', sa.Text(), nullable=False),
    sa.Column('result_payload_json', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatch_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goal_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_no >= 1', name='ck_execution_attempts_no_positive'),
    sa.ForeignKeyConstraint(['job_delivery_id'], ['job_material_deliveries.job_delivery_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['production_jobs.job_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_step_id'], ['job_steps.job_step_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('req_id')
    )
    op.create_index('ix_execution_attempts_job_delivery_id_command', 'execution_attempts', ['job_delivery_id', 'command_type'], unique=False)
    op.create_index('ix_execution_attempts_job_step_id_command', 'execution_attempts', ['job_step_id', 'command_type'], unique=False)
    op.create_index('ix_execution_attempts_status', 'execution_attempts', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_attempts_status', table_name='execution_attempts')
    op.drop_index('ix_execution_attempts_job_step_id_command', table_name='execution_attempts')
    op.drop_index('ix_execution_attempts_job_delivery_id_command', table_name='execution_attempts')
    op.drop_table('execution_attempts')
    # ### end Alembic commands ###
