"""Add failed_at to production_jobs"""
revision = '81d58e82d964'
down_revision = 'e5f0a58cbce2'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_jobs', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE production_jobs
        SET failed_at = pe.failed_at
        FROM (
            SELECT job_id, MAX(created_at) as failed_at
            FROM production_events
            WHERE event_type = 'JOB_FAILED'
            GROUP BY job_id
        ) pe
        WHERE production_jobs.job_id = pe.job_id
        AND production_jobs.status = 'FAILED'
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_jobs', 'failed_at')
    # ### end Alembic commands ###
