"""Add material_inspections table"""
revision = 'b1fcb137c6d8'
down_revision = '81d58e82d964'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_inspections',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspection_request_id', sa.String(length=100), nullable=False),
    sa.Column('delivery_item_id', sa.Integer(), nullable=False),
    sa.Column('inspection_cycle', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'RUNNING', 'COMPLETED', 'ERROR', name='material_inspection_status'), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'NOT_EVALUATED', name='material_inspection_result'), nullable=True),
    sa.Column('failure_type', sa.Enum('MISSING', 'WRONG_CLASS', 'QUANTITY_MISMATCH', 'DEFECT', 'MULTIPLE_FAILURE', name='material_inspection_failure_type'), nullable=True),
    sa.Column('expected_part_code', sa.String(length=100), nullable=False),
    sa.Column('expected_class_name', sa.String(length=100), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('detected_quantity', sa.Integer(), nullable=True),
    sa.Column('detections_json', sa.Text(), nullable=True),
    sa.Column('frame_width', sa.Integer(), nullable=True),
    sa.Column('frame_height', sa.Integer(), nullable=True),
    sa.Column('camera_source', sa.Enum('GLOBAL_CAMERA', 'D435', name='camera_source'), nullable=True),
    sa.Column('frame_seq', sa.Integer(), nullable=True),
    sa.Column('vision_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_scope', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('production_valid', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('inspection_cycle >= 1', name='ck_material_inspections_cycle'),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['job_material_delivery_items.delivery_item_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inspection_id'),
    sa.UniqueConstraint('delivery_item_id', 'inspection_cycle', name='uq_material_inspections_cycle'),
    sa.UniqueConstraint('inspection_request_id')
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('material_inspections')
    sa.Enum(name='material_inspection_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='material_inspection_result').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='material_inspection_failure_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='camera_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
